version: '3'



volumes:
  postgres_volume_local:
  postgres_volume_prod:


services:
  pg-local:
    image: postgres:14-alpine3.17
    env_file:
      - "local.env"
    ports:
      - "54321:5432"
    volumes:
      - postgres_volume_local:/var/lib/postgresql/data

#  migrator:
#    build:
#      context: .
#      dockerfile: migration.Dockerfile
#    restart: on-failure
#    environment:
#      DB_HOST: pg-local